// Generated by CoffeeScript 1.8.0
(function() {
  var app, db, express, level, request, unshorten;

  level = require('level');

  express = require('express');

  request = require('request');

  app = express();

  app.set('json spaces', 2);

  db = level('./unshrtndb');

  app.get("/", function(req, res) {
    var short;
    short = req.query.url;
    if (short) {
      return unshorten(short, db, function(error, long) {
        if (error) {
          return res.status(500).json({
            short: short,
            long: null,
            error: error
          });
        } else {
          console.log("" + short + " -> " + long);
          return res.json({
            short: short,
            long: long
          });
        }
      });
    } else {
      return res.status(400).json({
        short: null,
        long: null,
        error: "please supply url query parameter"
      });
    }
  });

  unshorten = function(short, db, callback) {
    if (short === null) {
      callback("short url cannot be null", null);
      return;
    }
    short = String(short);
    return db.get(short, function(err, long) {
      var error;
      if (!err) {
        return callback(null, long);
      } else {
        try {
          return request.get(short, {
            timeout: 10000
          }, function(error, r, body) {
            if (error) {
              return callback(String(error), null);
            } else if (r.statusCode !== 200) {
              return callback("HTTP " + r.statusCode, null);
            } else {
              long = String(r.request.uri.href);
              db.put(short, String(long));
              return callback(null, long);
            }
          });
        } catch (_error) {
          error = _error;
          return callback(error, null);
        }
      }
    });
  };

  if (require.main === module) {
    app.listen(3000);
  }

  exports.unshorten = unshorten;

}).call(this);
