// Generated by CoffeeScript 1.8.0
(function() {
  var app, db, express, jar, level, request, unshorten, userAgent;

  level = require('level');

  express = require('express');

  request = require('request');

  app = express();

  app.set('json spaces', 2);

  userAgent = "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.67 Safari/537.36";

  db = level('./unshrtndb');

  jar = request.jar();

  process.setMaxListeners(10);

  app.get("/", function(req, res) {
    var short;
    short = req.query.url;
    if (short) {
      return unshorten(short, db, function(error, long) {
        if (error) {
          return res.status(500).json({
            short: short,
            long: null,
            error: error
          });
        } else {
          console.log("" + short + " -> " + long);
          return res.json({
            short: short,
            long: long
          });
        }
      });
    } else {
      return res.status(400).json({
        short: null,
        long: null,
        error: "please supply url query parameter"
      });
    }
  });

  unshorten = function(short, db, callback) {
    if (short === null) {
      callback("short url cannot be null", null);
      return;
    }
    short = String(short);
    return db.get(short, function(err, long) {
      var error, opts;
      if (!err) {
        return callback(null, long);
      } else {
        try {
          opts = {
            url: short,
            jar: jar,
            timeout: 10000,
            headers: {
              "User-Agent": userAgent
            }
          };
          return request.get(opts, function(error, r, body) {
            if (error) {
              return callback(String(error), null);
            } else if (r.statusCode !== 200) {
              return callback("HTTP " + r.statusCode, null);
            } else {
              long = String(r.request.uri.href);
              db.put(short, String(long));
              return callback(null, long);
            }
          });
        } catch (_error) {
          error = _error;
          console.log(error);
          return callback(error, null);
        }
      }
    });
  };

  if (require.main === module) {
    app.listen(3000);
  }

  exports.unshorten = unshorten;

}).call(this);
